POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Mzg2MDUzNzYsInVzZXJJZCI6MX0.v7CWctMb6jlGGIIKu-FuBjLNGFdZnggV0FlNamPfGdw

{
  "name": "Test event",
  "description": "Test event!!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}